name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        rustup toolchain install nightly-x86_64-unknown-linux-gnu
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: target
        path: target/
